# @apiUrl = http://localhost:3000
# @apiUrl = https://36q4oc6xs2.execute-api.eu-west-1.amazonaws.com/prod
@apiUrl = https://d2rooolig6wbfk.cloudfront.net/api

@id = {{CreateUser.response.body.result.id}}
###

###
# @name CreateUser
POST {{apiUrl}}/users
Content-Type: application/json

{
  "email": "test@example.com"
}

###
# @name GetUser
GET {{apiUrl}}/users/{{id}}

###
# @name UpdateUser
PUT {{apiUrl}}/users/{{id}}
Content-Type: application/json

{
  "email": "updated@example.com"
}

###
# @name DeleteUser
DELETE {{apiUrl}}/users/{{id}}

